# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNFirebaseAnalytics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseAnalytics
	pod 'Firebase/Core'

  target 'RNFirebaseAnalytics-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNFirebaseAnalyticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNFirebaseAnalytics-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseAnalytics-tvOS

  #target 'RNFirebaseAnalytics-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end
